server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-user
              uri: http://k8s-backend-user-service:8080
              predicates:
                - Path=/api/user/**
            - id: backend-alim
              uri: http://k8s-backend-alim-service:8080
              predicates:
                - Path=/api/alim/**
            - id: backend-post
              uri: http://k8s-backend-post-service:8080
              predicates:
                - Path=/api/post/**

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gds3as54dfa32s1df2a6fwlkj298GsWg86G76745ADdjnfsk