server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: backend-user
              uri: http://localhost:8081
              predicates:
                - Path=/api/user/**

jwt:
  header: Authorization
  secret-key: AADfaskllew32dsfasdTG764Gds3as54dfa32s1df2a6fwlkj298GsWg86G76745ADdjnfsk